apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: registration-service
  description: |
    Registration service
  links:
    - title: Template
      url: http://arlo.com
  annotations:
    github.com/project-slug: harnessworkshop/idp-workshop
    backstage.io/techdocs-ref: dir:../
    lighthouse.com/website-url: https://arlo.com
  tags:
    - xcloud
    - registration
spec:
  type: service
  owner: xcloud
  lifecycle: production
  providesApis: 
    - registration-service-api
  system: XCloud