service:
  name: registration
  identifier: registration
  tags: {}
  organization: arloidp311org
  serviceDefinition:
    spec:
      manifests:
      variables:
    type: Kubernetes
  description: sample registration service