service:
  name: registration
  identifier: registration
  tags: {}
  orgIdentifier: arloidp311org
  projectIdentifier: XCloud
  serviceDefinition:
    spec:
      manifests:
      variables:
    type: Kubernetes
  description: sample registration service